### Importing libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### importing dataset

In [2]:
df=pd.read_csv(r"C:\Users\G0d\Downloads\housing_price_dataset.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   SquareFeet    50000 non-null  int64  
 1   Bedrooms      50000 non-null  int64  
 2   Bathrooms     50000 non-null  int64  
 3   Neighborhood  50000 non-null  object 
 4   YearBuilt     50000 non-null  int64  
 5   Price         50000 non-null  float64
dtypes: float64(1), int64(4), object(1)
memory usage: 2.3+ MB


#### Data Preprocessing

# EDA

In [4]:
df.isna().sum()

SquareFeet      0
Bedrooms        0
Bathrooms       0
Neighborhood    0
YearBuilt       0
Price           0
dtype: int64

In [5]:
df.duplicated().sum()

0

In [6]:
df.head()

SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt          Price
0        2126         4          1        Rural       1969  215355.283618
1        2459         3          2        Rural       1980  195014.221626
2        1860         2          1       Suburb       1970  306891.012076
3        2294         2          1        Urban       1996  206786.787153
4        2130         5          2       Suburb       2001  272436.239065

neighbourhood here it is in chatagerical data so we have to convert the char data to numerical data by using feature TRANSFORMATONS
in this tansformations we have to use oridinal methoad because the char dta is following some order rural>suburban and suburban>urban

In [7]:
#def ordinal

In [8]:
df['Neighborhood']=df['Neighborhood'].map({'Rural':1,'Suburb':2,'Urban':3})


In [9]:
df.head()

SquareFeet  Bedrooms  Bathrooms  Neighborhood  YearBuilt          Price
0        2126         4          1             1       1969  215355.283618
1        2459         3          2             1       1980  195014.221626
2        1860         2          1             2       1970  306891.012076
3        2294         2          1             3       1996  206786.787153
4        2130         5          2             2       2001  272436.239065

## Model Building

#### splitting into input and output

In [10]:
A=df['YearBuilt']

In [11]:
min(A),max(A)

(1950, 2021)

In [12]:
X=df.drop('Price',axis=1)
y=df['Price']

In [13]:
!pip install scikit-learn

In [14]:
y

0        215355.283618
1        195014.221626
2        306891.012076
3        206786.787153
4        272436.239065
             ...      
49995    100080.865895
49996    374507.656727
49997    384110.555590
49998    380512.685957
49999    221618.583218
Name: Price, Length: 50000, dtype: float64

#### Splitting into TRAIN and TEST

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
train_test_split(X,y, test_size=0.2,random_state=23)

[       SquareFeet  Bedrooms  Bathrooms  Neighborhood  YearBuilt
 20198        2169         2          3             1       1988
 34103        2568         3          2             2       1977
 40179        1339         3          3             1       1958
 34586        2716         2          1             1       1978
 30725        2307         3          1             1       1974
 ...           ...       ...        ...           ...        ...
 9704         2788         4          3             2       1986
 11190        2557         5          1             2       2004
 26569        2344         3          2             1       1961
 9256         1105         5          2             2       2008
 41555        2248         2          3             3       2020
 
 [40000 rows x 5 columns],
        SquareFeet  Bedrooms  Bathrooms  Neighborhood  YearBuilt
 49466        1055         3          2             1       1969
 11621        1754         4          3             1       1

In [17]:
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.2,random_state=23)

In [18]:
X_train.shape

(40000, 5)

In [19]:
y_train.shape

(40000,)

In [20]:
X_test.shape

(10000, 5)

In [21]:
y_test.shape

(10000,)

#### KNN,Linear Regression,SVM,DT

#### KNN

In [22]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error,r2_score

In [23]:
knn=KNeighborsRegressor()
knn.fit(X_train,y_train)
y_pred=knn.predict(X_test)
print(np.sqrt(mean_squared_error(y_test,y_pred)))

54247.93901533543


### Evaluating - how knn work

In [24]:
from sklearn.metrics import mean_squared_error,r2_score

### Linear regression

In [25]:
from sklearn.linear_model import LinearRegression


In [26]:
lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred=lr.predict(X_test)
print(np.sqrt(mean_squared_error(y_test,y_pred)))

49403.976927995944


### Support Vector Regression

In [46]:
from sklearn.svm import SVR

In [ ]:
sv=SVR()
sv.fit(X_train,y_train)
y_pred=sv.predict(X_test)
print(np.sqrt(mean_squared_error(y_test,y_pred)))

### Decision Tree

In [27]:
from sklearn.tree import DecisionTreeRegressor

In [28]:
dt=DecisionTreeRegressor()
dt.fit(X_train,y_train)
y_pred=dt.predict(X_test)
print(np.sqrt(mean_squared_error(y_test,y_pred)))

72263.27866798923


In [29]:
lr.predict([[2250,5,2,3,2002]])[[0]]

C:\Users\G0d\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([257199.22508665])

In [30]:
lr.coef_

array([  99.31308607, 5168.85659283, 2625.12603247,  752.26187692,
        -13.64933459])

In [31]:
lr.intercept_

27719.42860046134

In [32]:
sqft=2250
bed=5
bath=2
nb=3
year=2002
price=99.31308607*sqft+5168.85659283*bed+2625.12603247*bath+752.26187692*nb -13.64933459*year+27719.42860046134

In [33]:
print(price)

257199.22506863135


# Pickling

In [34]:
import pickle

In [35]:
pickle.dump(lr,open('lr.pkl','wb'))    ##writing as a binary format file

In [36]:
model=pickle.load(open('lr.pkl','rb'))

In [37]:
model.predict([[2126,4,1,1,1969]])

C:\Users\G0d\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([236036.32407558])